# GATE 1 — STRUCTURED PAGE RESEARCH for Brunner Law Firm (direct reads, 2026-09-13)
structured_pages = [
 {"exact_url":"https://thebrunnerlawfirm.com/","page_type":"homepage",
  "actual_offer":"Texas criminal defense representation (misdemeanor to felony, state + federal)",
  "actual_heading":"Texas Criminal Defense",
  "cta_text":"Free Consultation / Case Evaluation","cta_destination":"/contact.html",
  "price_info":"Fees depend on charge/complexity; flat fees for most matters (in practice-area text)",
  "minimum_info":"","turnaround_info":"Monday-Friday 9:00 AM-6:00 PM CT",
  "proof_info":"Practice-area descriptions + blog; no case results/testimonials list",
  "buyer_questions_answered":"Who we are; what practice areas; initial consultation offered",
  "buyer_questions_not_answered":"What to do right after an arrest before calling; fee ranges by charge; what happens in first consultation",
  "direct_evidence_excerpt":"The Brunner Law Firm provides dedicated criminal defense representation... Reach out for a confidential consultation and an honest assessment of where you stand."},
 {"exact_url":"https://thebrunnerlawfirm.com/practice-areas.html","page_type":"nav_hub",
  "actual_offer":"Full range of Texas criminal defense practice areas",
  "actual_heading":"Practice Areas",
  "cta_text":"Free Consultation","cta_destination":"/contact.html",
  "price_info":"","minimum_info":"","turnaround_info":"",
  "proof_info":"",
  "buyer_questions_answered":"Which criminal defense areas covered",
  "buyer_questions_not_answered":"Which charge applies to my specific situation; fee guidance per practice area",
  "direct_evidence_excerpt":"Criminal defense is what we do... from misdemeanor citations to first-degree felonies."},
 {"exact_url":"https://thebrunnerlawfirm.com/practice-areas/criminal-defense.html","page_type":"service",
  "actual_offer":"Comprehensive criminal defense (misdemeanor + felony, TX state + federal)",
  "actual_heading":"Criminal Defense",
  "cta_text":"Free Consultation","cta_destination":"/contact.html",
  "price_info":"Flat fees for most matters; payment plans available",
  "minimum_info":"","turnaround_info":"",
  "proof_info":"Case preparation described (discovery, witness interviews, motion practice); no case outcomes listed",
  "buyer_questions_answered":"Coverage of offenses; how case prep works",
  "buyer_questions_not_answered":"What to do immediately after arrest; fee range by charge; how long case takes",
  "direct_evidence_excerpt":"Comprehensive defense for misdemeanor and felony charges across Texas state and federal courts."},
 {"exact_url":"https://thebrunnerlawfirm.com/practice-areas/dwi-dui-defense.html","page_type":"service",
  "actual_offer":"DWI/DUI defense incl. license suspension hearings",
  "actual_heading":"DWI / DUI Defense",
  "cta_text":"Free Consultation","cta_destination":"/contact.html",
  "price_info":"","minimum_info":"","turnaround_info":"",
  "proof_info":"",
  "buyer_questions_answered":"DWI/DUI coverage + license suspension",
  "buyer_questions_not_answered":"What to do after a stop/arrest; typical fee; license-suspension process steps",
  "direct_evidence_excerpt":"Strategic defense against drunk driving allegations, including license suspension hearings."},
 {"exact_url":"https://thebrunnerlawfirm.com/practice-areas/drug-crimes.html","page_type":"service",
  "actual_offer":"Drug crimes defense (possession, distribution, manufacturing)",
  "actual_heading":"Drug Crimes",
  "cta_text":"Free Consultation","cta_destination":"/contact.html",
  "price_info":"","minimum_info":"","turnaround_info":"",
  "proof_info":"",
  "buyer_questions_answered":"Drug charge coverage",
  "buyer_questions_not_answered":"What to do if charged; fee; sentencing exposure",
  "direct_evidence_excerpt":"Representation for possession, distribution, and manufacturing charges under Texas drug laws."},
 {"exact_url":"https://thebrunnerlawfirm.com/blog/what-to-do-after-an-arrest-in-texas.html","page_type":"blog",
  "actual_offer":"Educational guide: what to do after a Texas arrest",
  "actual_heading":"What To Do After an Arrest in Texas: A Step by Step Guide",
  "cta_text":"Free Consultation / Case Evaluation","cta_destination":"/contact.html",
  "price_info":"","minimum_info":"","turnaround_info":"",
  "proof_info":"Educational content builds authority/trust",
  "buyer_questions_answered":"What to do immediately after an arrest",
  "buyer_questions_not_answered":"Cost of defense; how to choose a lawyer; do-not-act list application",
  "direct_evidence_excerpt":"What To Do After an Arrest in Texas: A Step by Step Guide..."},
 {"exact_url":"https://thebrunnerlawfirm.com/contact.html","page_type":"contact",
  "actual_offer":"Contact / free case consultation request",
  "actual_heading":"Contact Us / Free Consultation",
  "cta_text":"Free Consultation / Case Evaluation","cta_destination":"(form submit)",
  "price_info":"","minimum_info":"","turnaround_info":"Monday-Friday 9:00 AM-6:00 PM CT",
  "proof_info":"",
  "buyer_questions_answered":"How to contact; form fields (name/email/practice/subject/message)",
  "buyer_questions_not_answered":"When I'll be contacted; whether consultation is really free; next steps",
  "direct_evidence_excerpt":"Form fields: name, email, practice, subject, message. Free Consultation / Contact Us."},
 {"exact_url":"https://thebrunnerlawfirm.com/about.html","page_type":"about",
  "actual_offer":"Firm background / attorney credibility",
  "actual_heading":"About / Attorney",
  "cta_text":"Free Consultation","cta_destination":"/contact.html",
  "price_info":"","minimum_info":"","turnaround_info":"",
  "proof_info":"Attorney background/credibility",
  "buyer_questions_answered":"Who the attorney is",
  "buyer_questions_not_answered":"Credentials detail, bar membership, experience length",
  "direct_evidence_excerpt":"About the Brunner Law Firm..."},
]