# GATE 1 — STRUCTURED PAGE RESEARCH for Apple Imprints (from direct reads, 2026-09-13)
# Each relevant customer-owned page gets the full structured schema.
structured_pages = [
 {"exact_url":"https://appleimprints.com/","page_type":"homepage",
  "actual_offer":"Custom apparel decoration: screen printing, embroidery, DTG, DTF, debossing",
  "actual_heading":"Your Brand. Our Mission.",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"",
  "buyer_questions_answered":"What services do you offer",
  "buyer_questions_not_answered":"How much does it cost; what is the minimum order; how fast can you deliver",
  "direct_evidence_excerpt":"High-quality screen printing that makes your brand stand out. From tees to hoodies..."},
 {"exact_url":"https://appleimprints.com/screen-printing/","page_type":"service",
  "actual_offer":"Screen printing (spot color, 4-color process, simulated, specialty)",
  "actual_heading":"Apple Imprint's Screen Printing Services",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"",
  "buyer_questions_answered":"What screen-printing methods are available",
  "buyer_questions_not_answered":"Minimum order; price range; per-piece price; turnaround",
  "direct_evidence_excerpt":"Apple Imprint's offers a variety of different screen printing..."},
 {"exact_url":"https://appleimprints.com/embroidery/","page_type":"service",
  "actual_offer":"Embroidery (polos, hats, professional stitching)",
  "actual_heading":"Apple Imprint's Embroidery Services",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"",
  "buyer_questions_answered":"What is embroidery; professional appearance",
  "buyer_questions_not_answered":"Minimum order; price; turnaround; digitising fee",
  "direct_evidence_excerpt":"Embroidery adds a classic, high-end look..."},
 {"exact_url":"https://appleimprints.com/get-a-quote-2/","page_type":"quote",
  "actual_offer":"Quote request for custom apparel order",
  "actual_heading":"Get A Quote!",
  "cta_text":"Submit quote form","cta_destination":"(form submit)",
  "price_info":"","minimum_info":"","turnaround_info":"Within 24 hours or less! If rush is needed, please call us!",
  "proof_info":"",
  "buyer_questions_answered":"How do I submit a quote; how fast is reply",
  "buyer_questions_not_answered":"What happens after I submit; why trust this shop; what will it cost",
  "direct_evidence_excerpt":"Within 24 hours or less! If rush is needed, please call us! First Name * Last Name * Email Address * Phone"},
 {"exact_url":"https://appleimprints.com/gallery/","page_type":"gallery_proof",
  "actual_offer":"Completed order examples of custom apparel decoration",
  "actual_heading":"Our Works",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"gallery exists (unlabelled image wall)",
  "buyer_questions_answered":"Can I see completed work",
  "buyer_questions_not_answered":"Which technique was used per piece; how does this map to my project; any testimonials",
  "direct_evidence_excerpt":"browse our gallery of completed orders that have satisfied..."},
 {"exact_url":"https://appleimprints.com/about/","page_type":"about",
  "actual_offer":"Company story / trust",
  "actual_heading":"WHO ARE WE? / OUR STORY",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"story + family/community values",
  "buyer_questions_answered":"Who is behind Apple Imprints",
  "buyer_questions_not_answered":"Credentials, guarantees, delivery/support",
  "direct_evidence_excerpt":"Apple Imprints comes from humble beginnings with a strong sense of family and community..."},
 {"exact_url":"https://appleimprints.com/contact/","page_type":"contact",
  "actual_offer":"Direct contact",
  "actual_heading":"CONTACT US",
  "cta_text":"Send Us a Message","cta_destination":"(contact form)",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"",
  "buyer_questions_answered":"How to reach the company (address/phone)",
  "buyer_questions_not_answered":"Pricing; order process",
  "direct_evidence_excerpt":"2336 Bailey Avenue, Buffalo, ny, 14211 716-89..."},
 {"exact_url":"https://appleimprints.com/equipment/","page_type":"about",
  "actual_offer":"Production capability/trust",
  "actual_heading":"Equipment We Use",
  "cta_text":"Get a Quote","cta_destination":"/get-a-quote-2/",
  "price_info":"","minimum_info":"","turnaround_info":"","proof_info":"equipment list",
  "buyer_questions_answered":"What equipment do you use",
  "buyer_questions_not_answered":"Pricing; minimums; turnaround",
  "direct_evidence_excerpt":"Equipment We Use..."},
]